# Generated by Django 2.2.14 on 2020-07-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastNAme', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='Clase.Clase')),
            ],
        ),
    ]
