# Generated by Django 2.2.14 on 2020-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('n_student', models.IntegerField(verbose_name=3)),
                ('professor', models.CharField(max_length=50)),
                ('schedule', models.DateTimeField()),
            ],
        ),
    ]
